theme: jekyll-theme-minimal
title: Caroline Zambon
description: email: cazambon@gmail.com
description: phone: 312 918-0899
description: linkedin: [caroline-zambon](https://www.linkedin.com/in/caroline-zambon/)
description: Results-oriented, creative professional with 8+ years of experience working with design systems and collaborating with multidisciplinary teams to develop innovative designs and graphic materialsto promote clients’ and companies’ creative visions. Excellent time management, organization, teamwork, problem-solving, and communication skills. Fluency in English and Portuguese. Awarded Honorable Mention in the category of Product Design from 6th Encuentro BID for final graduation project and received invitation to present the project at the Young Designers Exhibitions and FAUFORMA in Sao Paulo, Brazil.
